# Generated by Django 4.2.2 on 2023-07-27 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_chats', to='eventech.event')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventech.attendee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
