# Generated by Django 4.2.2 on 2023-07-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventech', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
