# Generated by Django 4.2.2 on 2023-07-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventech", "0002_delete_adminuser_adminuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventRequest",
        ),
    ]
