# Generated by Django 4.2.2 on 2023-07-10 22:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("eventech", "0003_delete_eventrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_description", models.TextField()),
                ("event_location", models.CharField(max_length=255)),
                ("requester_name", models.CharField(max_length=255)),
                ("requester_email", models.EmailField(max_length=254)),
                ("requester_phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventech.adminuser",
                    ),
                ),
                (
                    "Attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventech.attendee",
                    ),
                ),
            ],
        ),
    ]
