# Generated by Django 4.2.2 on 2023-07-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eventech", "0004_eventrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="admin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="eventech.adminuser",
            ),
            preserve_default=False,
        ),
    ]
