# Generated by Django 4.2.2 on 2023-07-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventech', '0005_event_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrequest',
            old_name='Admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='eventrequest',
            old_name='Attendee',
            new_name='attendee',
        ),
    ]
