# Generated by Django 4.2.2 on 2023-07-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventech', '0006_rename_admin_eventrequest_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
