# Generated by Django 4.2.2 on 2023-07-24 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventech', '0007_eventattendee_attended'),
        ('eventech', '0008_initial'),
    ]

    operations = [
    ]
